#pragma once

#include <estd/port/arch/version.h>

#define EMBR_COAP_VER_MAJOR     ${PROJECT_VERSION_MAJOR}
#define EMBR_COAP_VER_MINOR     ${PROJECT_VERSION_MINOR}
#define EMBR_COAP_VER_PATCH     ${PROJECT_VERSION_PATCH}

#define EMBR_COAP_VER  ESTD_BUILD_SEMVER(${PROJECT_VERSION_MAJOR}, ${PROJECT_VERSION_MINOR}, ${PROJECT_VERSION_PATCH})
#define EMBR_COAP_VER_STR "${PROJECT_VERSION_MAJOR}.${PROJECT_VERSION_MINOR}.${PROJECT_VERSION_PATCH}"
