
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;

	private global::Gtk.Button button2;

	private global::Gtk.ComboBoxEntry lstURI;

	private global::Gtk.CheckButton chkConfirmable;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button2 = new global::Gtk.Button();
		this.button2.CanFocus = true;
		this.button2.Name = "button2";
		this.button2.UseUnderline = true;
		this.button2.Label = global::Mono.Unix.Catalog.GetString("Request");
		this.fixed1.Add(this.button2);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button2]));
		w1.X = 33;
		w1.Y = 25;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lstURI = global::Gtk.ComboBoxEntry.NewText();
		this.lstURI.Name = "lstURI";
		this.fixed1.Add(this.lstURI);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lstURI]));
		w2.X = 164;
		w2.Y = 23;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.chkConfirmable = new global::Gtk.CheckButton();
		this.chkConfirmable.CanFocus = true;
		this.chkConfirmable.Name = "chkConfirmable";
		this.chkConfirmable.Label = global::Mono.Unix.Catalog.GetString("Confirmable");
		this.chkConfirmable.DrawIndicator = true;
		this.chkConfirmable.UseUnderline = true;
		this.fixed1.Add(this.chkConfirmable);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.chkConfirmable]));
		w3.X = 167;
		w3.Y = 91;
		this.Add(this.fixed1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 422;
		this.DefaultHeight = 300;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.button2.Clicked += new global::System.EventHandler(this.OnButton2Clicked);
	}
}
