#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := dtls-datapump

# for PIO compatibility
#CPPFLAGS := -DESP32

include $(IDF_PATH)/make/project.mk